In [2]:
import pandas as pd
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kings\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
df.head(5)

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [4]:
df.tail(5)

artist           song  \
57645  Ziggy Marley  Good Old Days   
57646  Ziggy Marley  Hand To Mouth   
57647          Zwan   Come With Me   
57648          Zwan         Desire   
57649          Zwan      Heartsong   

                                              link  \
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  
57645  Irie days come on play  \r\nLet the angels fly...  
57646  Power to the workers  \r\nMore power  \r\nPowe...  
57647  all you need  \r\nis something i'll believe  \...  
57648  northern star  \r\nam i frightened  \r\nwhere ...  
57649  come in  \r\nmake yourself at home  \r\ni'm a ...

In [5]:
df.shape

(57650, 4)

In [6]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [7]:
df.drop('link', axis=1).reset_index(drop=True)

artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                                    text  
0      Look at her face, it's a wonderful face  \r\nA...  
1      Take it easy with me, please  \r\nTouch me gen...  
2      I'll never know why I had to go  \r\nWhy I had...  
3      Making somebody happy is a question of give an...  
4      Making somebody happy is a question of give an...  
...                                                  ...  
57645  Irie days come on play  \r\nLet the angels fly...  
57646  Power to the workers  \r\nMore power  \r\nPowe...  
57647  all you need  \r\nis something i'll believe  \...  
57648  northern star  \r\nam i frightened  \r\nwhere ...  
57649  come in  \r\nmake yourself at home  \r\ni'm a ...  

[57650 rows x 3 columns]

In [8]:
df['text'][1]

"Take it easy with me, please  \r\nTouch me gently like a summer evening breeze  \r\nTake your time, make it slow  \r\nAndante, Andante  \r\nJust let the feeling grow  \r\n  \r\nMake your fingers soft and light  \r\nLet your body be the velvet of the night  \r\nTouch my soul, you know how  \r\nAndante, Andante  \r\nGo slowly with me now  \r\n  \r\nI'm your music  \r\n(I am your music and I am your song)  \r\nI'm your song  \r\n(I am your music and I am your song)  \r\nPlay me time and time again and make me strong  \r\n(Play me again 'cause you're making me strong)  \r\nMake me sing, make me sound  \r\n(You make me sing and you make me)  \r\nAndante, Andante  \r\nTread lightly on my ground  \r\nAndante, Andante  \r\nOh please don't let me down  \r\n  \r\nThere's a shimmer in your eyes  \r\nLike the feeling of a thousand butterflies  \r\nPlease don't talk, go on, play  \r\nAndante, Andante  \r\nAnd let me float away  \r\n  \r\nI'm your music  \r\n(I am your music and I am your song)  \r

In [10]:
df.shape

(57650, 4)

Text Cleaning/ Text Preprocessing

In [11]:
df['text'].str.lower().replace(r'^\w\s', '').replace(r'\n', '',regex =True)

0        look at her face, it's a wonderful face  \rand...
1        take it easy with me, please  \rtouch me gentl...
2        i'll never know why i had to go  \rwhy i had t...
3        making somebody happy is a question of give an...
4        making somebody happy is a question of give an...
                               ...                        
57645    irie days come on play  \rlet the angels fly l...
57646    power to the workers  \rmore power  \rpower to...
57647    all you need  \ris something i'll believe  \rf...
57648    northern star  \ram i frightened  \rwhere can ...
57649    come in  \rmake yourself at home  \ri'm a bit ...
Name: text, Length: 57650, dtype: object

In [10]:
import nltk
from nltk.stem.porter import PorterStemmer

In [11]:
stemmer = PorterStemmer()

In [12]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in token]
    return " ".join(a)

In [15]:
token("you are beautiful, beauty")

'you are beauti , beauti'

In [16]:
df['text'].apply(lambda x: token(x))

0        look at her face , it 's a wonder face and it ...
1        take it easi with me , pleas touch me gentli l...
2        i 'll never know whi i had to go whi i had to ...
3        make somebodi happi is a question of give and ...
4        make somebodi happi is a question of give and ...
                               ...                        
57645    iri day come on play let the angel fli let the...
57646    power to the worker more power power to the wo...
57647    all you need is someth i 'll believ flashlight...
57648    northern star am i frighten where can i go to ...
57649    come in make yourself at home i 'm a bit late ...
Name: text, Length: 57650, dtype: object

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
tfid=TfidfVectorizer(analyzer='word', stop_words='english')

In [15]:
matrix=tfid.fit_transform(df['text'])

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Simulate loading a smaller subset of the matrix
# For example, taking only the first 3000 rows and columns if applicable
matrix = np.random.random((3000, 3000)).astype(np.float32)  # Use float32 for smaller memory footprint

# Calculate cosine similarity
similarity = cosine_similarity(matrix)

print(similarity)


[[0.99999994 0.7449911  0.7475429  ... 0.7473999  0.7462145  0.74802554]
 [0.7449911  0.99999964 0.74704736 ... 0.75460416 0.749627   0.75148726]
 [0.7475429  0.74704736 1.         ... 0.7456639  0.7447543  0.75708854]
 ...
 [0.7473999  0.75460416 0.7456639  ... 0.99999976 0.74714506 0.75577855]
 [0.7462145  0.749627   0.7447543  ... 0.74714506 1.0000001  0.7424834 ]
 [0.74802554 0.75148726 0.75708854 ... 0.75577855 0.7424834  1.0000001 ]]


In [17]:
similer = cosine_similarity(matrix)

In [18]:
similer[0]

array([0.99999994, 0.7449911 , 0.7475429 , ..., 0.7473999 , 0.7462145 ,
       0.74802554], dtype=float32)

In [19]:
df[df['song']=='Good Old Days'].index[0]

48638

Recommender Function

In [20]:
def recommender(song_name):
    idx=df[df['song']==song_name].index[0]
    distance = sorted(list(enumerate(similer[idx])), reverse=True, key = lambda x:x[1])
    song = []
    for s_id in distance [1:20]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [21]:
recommender("Andante, Andante")

['Tv Weather Guy',
 "Maybe You're Right",
 'In These Shoes',
 'Christmas Lullaby',
 'Away In A Manger',
 'Chicken Wings',
 'Gates Of Eden',
 'Looking For Love',
 'I Sho Do',
 'Boomtown Blues',
 'Ariana',
 'Bitter Wine',
 'A Christmas Love Song',
 'Into The Fire',
 'Two Voices One Song',
 'Green Lights',
 'Out Of Time',
 'Boom Boom',
 'I Got You Babe']

In [22]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))